name: Build and run tests
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository and submodules
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Run Tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          report_name: furball_tests
          report_title: Furball Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
